name: integration tests (INTR)

on:
    push:
        branches:
            - master

concurrency:
    group: ${{ github.ref }}_intr
    cancel-in-progress: true

jobs:
    test_intr:
        uses: ./.github/workflows/reusable-wf-integration-tests.yml
        with:
            parachain: INTR
