name: integration tests (Kintsugi)

on:
    pull_request:
        branches:
            - master

concurrency:
    group: ${{ github.ref }}_kintsugi
    cancel-in-progress: true

jobs:
    test_kintsugi:
        uses: ./.github/workflows/reusable-wf-integration-tests.yml
        with:
            parachain: kintsugi
