name: integration tests (KINT)

on:
    pull_request:
        branches:
            - master

concurrency:
    group: ${{ github.ref }}_kint
    cancel-in-progress: true

jobs:
    test_kint:
        uses: ./.github/workflows/reusable-wf-integration-tests.yml
        with:
            parachain: KINT
