name: integration test (INTR)

on:
# todo: remove pull request trigger after initial tests
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

concurrency:
  group: ${{ github.ref }}_intr
  cancel-in-progress: true

jobs:
  test_intr:
    uses: ./.github/workflows/test-release-reusable.yml
    with:
      parachain: INTR
