name: integration test

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'

jobs:
    build:
        runs-on: [self-hosted, linux]
        steps:
            - uses: actions/checkout@v2
            - name: setup node
              uses: actions/setup-node@v2
              with:
                  node-version: "16"
            - run: corepack enable
            - run: yarn install
            - name: Run and set up the parachain, oracle, staked relayer and vault
              run: yarn docker-parachain-start -- -d
            - run: yarn ci:test
