name: integration test

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
    build:
        runs-on: [self-hosted, linux]
        timeout-minutes: 60
        steps:
            - uses: actions/checkout@v2
            - name: setup node
              uses: actions/setup-node@v2
              with:
                  node-version: "16"
            - run: corepack enable
            - run: yarn install
            - name: Check versions
              run: | 
                yarn --version
                npx node --version
                npx ts-node --version
            - name: Run and set up the parachain, oracle, staked relayer and vault
              run: yarn docker-parachain-start -- -d
            - run: yarn ci:test

            - name: Archive Docker logs
              if: always()
              run: docker-compose -f local-setup/docker-compose.yml logs > logs.txt

            - name: Upload logs
              if: always()
              uses: actions/upload-artifact@v3
              with:
                name: docker-compose-logs
                path: logs.txt

